export const theme = {
  colors: {
    // Core palette: white, black, yellow, purple, orange, green
    white: '#FFFFFF',
    black: '#0A0A0A',
    yellow: '#FACC15',
    yellowDark: '#EAB308',
    purple: '#7C3AED',
    purpleLight: '#8B5CF6',
    purpleDark: '#5B21B6',
    orange: '#F97316',
    orangeLight: '#FB923C',
    orangeDark: '#EA580C',
    green: '#22C55E',
    greenLight: '#4ADE80',
    greenDark: '#16A34A',
    // Semantic mappings
    primary: '#7C3AED',
    primaryLight: '#8B5CF6',
    primaryDark: '#5B21B6',
    secondary: '#FACC15',
    accent: '#F97316',
    background: '#FFFFFF',
    surface: '#FAFAFA',
    text: '#0A0A0A',
    textSecondary: '#525252',
    error: '#DC2626',
    success: '#22C55E',
    cash: '#FACC15',
    card: '#F5F5F5',
  },
  fonts: {
    regular: 'System',
    bold: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    full: 9999,
  },
};
